### ISSUE TITLE
[Epic] Inscription

### ISSUE THREAD

**Issue by ndeloof** [breizhcamp/camaaloth#1]
En tant que (futur) participant
Je veux pouvoir
- sélectionner un tarif
- saisir mes informations participant
- saisir mes informations acheteur (si différent)
- valider mon achat

**Comment by alexthomazo** [comment]
3 personnes interviennent pendant le processus de réservation de billet (pouvant être la même personne) : 
- acheteur
- payeur
- participant

L'acheteur arrive sur le site et réserve les places qu'il désire. Il sélectionne s'il veux payer tout de suite en carte (redirection vers la page de paiement) ou plus tard (envoi d'un lien par mail)

Le payeur utilise sa carte pour régler le montant des billets (cf #7 )

Une fois les billets réglés, l'acheteur peut assigner les billets aux participants (nom, prénom, mail), le participant reçoit un mail de confirmation qui lui permet de modifier ses infos (cf #6)

=> Il s'agit du workflow "must have", dans un 1er temps on part du principe qu'il s'agit de la même personne qui fait les 3 actions

**Comment by ndeloof** [comment]
tldr; privilégier le cas le plus simple pour les 75% d'usager qui payent directement leur place.

Je mettrais le paiement différé en très basse priorité. Ca aura du sens si on accepte les paiement par virement / mandat administratif ou autres. Un paiement par carte ne nécessite pas un délais (et ça évite de bloquer une place pendant X heures)

Pour l'affectation des billets à un participant, le faire après paiement n'est pas très naturel pour les cas simples (i.e autres que Capgematos). On peut se focaliser sur un scénario beaucoup plus simple et reposer sur #6 (édition du participant) pour les usages plus ... asynchrones.
