### ISSUE TITLE
Soucis l'année dernière

### ISSUE THREAD

**Issue by bmagic** [breizhcamp/camaaloth#12]
J'ai testé cette configuration l'année dernière à l'université de Rennes et cela n'a pas fonctionné. 

Il y a des soucis de résolution avec les vidéos projecteurs et la convertion qui est faite en amont dans la salle 
... 
Le pc du poste va se synchroniser dans une résolution maximale (1920 x 1080 par exemple) avec la blackmagic et du coup la sortie VGA ou HDMI sera dans cette résolution, il n'est pas possible de la changer à ma connaissance.

Du coup le convertisseur Fixe de la salle (VGA vers HDMI) va recevoir du 1920x1080 et il n'aime pas ça vu qu'il veut du 4/3 pour prendre tout l'écran.

Bref la seule solution est de fixer la résolution d'entrée sur la Blackmagic 4K mais cela demande une intervention à chaque PC branché.

**Comment by ydubreuil** [comment]
L'idée était d'utiliser la sortie VGA du PC configuré en 1280x1024 et avec OBS de faire du scaling / crop / resize de l'entrée HDMI du PC de presentation. OBS a des nouvelles options depuis la 0.16 qui semble permettre de faire ça.

Évidemment, il faut que les slides soit au format 4/3, sinon, il va en manquer un bout.

**Comment by alexthomazo** [comment]
Hello,

Je te confirme qu'on a fait le downscale en 1280x1024 via OBS, l'entrée vidéoprojecteur étant branchée directement sur la sortie VGA de notre PC de capture. La recopie HDMI de la blackmagic 4k n'étant du coup pas utilisée.

On a depuis investi dans un HD Fury (voir #15) pour forcer le PC Speaker à sortir en 720p50 mais permettant de forcer la sortie dans une autre résolution si besoin.
