### ISSUE TITLE
Matrox Monarch LCS

### ISSUE THREAD

**Issue by bmagic** [breizhcamp/camaaloth#13]
Pour information Monarch a sorti ça : 
http://www.matrox.com/video/fr/products/monarch_lcs/
2500€ HT 

Ca a des avantages comme l'installation facile et le début de l'enregistrement sur un bouton, mais c'est moins paramétrable au niveau de la réalisation vidéo que OBS.

**Comment by alexthomazo** [comment]
Hello,

Merci pour l'info, mais à ce tarif là et vu nos contraintes, on a de quoi ce payer pas mal de matos Blackmagic bien plus souple :)
