### ISSUE TITLE
Update sur le matériel

### ISSUE THREAD

**Issue by bmagic** [breizhcamp/camaaloth#15]
Salut, 
c'est possible d'avoir un update sur le matériel qui est présent actuellement dans la malette en détail ?
J'aimerai avoir une idée du coût de la régie que vous avez monté au final.

Merci d'avance.

**Comment by alexthomazo** [comment]
Hello,
Désolé, je ne sais pas pourquoi, GitHub ne m'a pas envoyé de notif pour ce repos.

Nous sommes en train de préparer la version 2 pour le BreizhCamp 2018, notamment en passant en SDI pour éviter les problèmes de clock HDMI, de synchro son... (#teamperfectionnistes)

A l'heure actuelle, voici le matos de capture vidéo :
* Un pc "classique" Core i5 moyenne gamme, 8Go de RAM, Ubuntu studio
* 2 cartes Blackmagic decklink mini recorder pour les entrées caméras
* 1 carte Blackmagic decklink Studio 4k (son équivalent ancien modèle pour être exact), nous permet de capturer les slides et de recopier ceux-ci en HDMI vers le vidéo projecteur
* 1 [HD Fury](https://www.amazon.fr/HD-Fury-Convertisseurs-Dr-HDMI/dp/B00755DBCW/ref=sr_1_2?ie=UTF8&qid=1511462672&sr=8-2&keywords=hd+fury) avec l'EDID [720p50](https://github.com/breizhcamp/camaaloth/tree/master/edid) qui nous permet de forcer la résolution en sortie du PC Speaker
* OBS pour l'enregistrement

Pour l'audio :
* un micro serre tête [Sennheiser HSP 2 EW 3](https://www.thomann.de/fr/sennheiser_hsp_2_ew_beige.htm?ref=search_rslt_Sennheiser+HSP+2+EW+3_180805_1)
* couplé à un transmetteur [Sennheiser AVX](https://www.thomann.de/fr/sennheiser_avx_mke2_set.htm?ref=search_prv_4)
* une table de mixage [Behringer](https://www.thomann.de/fr/behringer_xenyx_q802_usb.htm) d'entrée de gamme
* une carte son PCI

Les petits problèmes qu'on a avec ce setup :
* saute d'image HDMI de la caméra, on pense que c'est un problème de clock HDMI
* forcer le 720p sur le PC du speaker c'est pas top, dès fois ça marche même pas, et ça réduit la qualité de la recopie, on compte investir dans un Decimator MD-HX pour nous faire un downscale en 720p mais garder une recopie en Full HD
* désynchro son/image : avec OBS, on a pas qq chose de stable sur la latence entre l'image et le son, on regarde du côté de [nageru](https://nageru.sesse.net/) ou de [CasparCG](https://casparcg.com/) pour remplacer OBS. On a aussi investi dans un transmetteur Sennheiser sans latence (je n'ai pas la ref sous la main)
* volume son pas très bien géré : on compte changer de table de mixage pour en prendre une avec compresseur (volume auto pour faire simple) ou bien utiliser le compresseur logiciel de nageru qui semble plutôt pas mal

De plus, pour le BreizhCamp, on aimerai afficher des infos sur le vidéoprojecteur entre 2 sessions (possible avec le Decimator), contrôler nos lumières (DMX), passer une vidéo d'intro d'où l'upgrade de matos.

Voilà, n'hésites pas si tu as d'autres questions :)

**Comment by bmagic** [comment]
Merci pour la réponse (et les autres au passage), vous commencez à être bien équipés c'est cool :) 
Du coup vous allez basculer dans le semipro avec le SDI qui devrait effectivement résoudre pas mal de soucis.
